### PR TITLE
gomod: update version

### PR DESCRIPTION
**Pull request by sivchari**
I've updated Go module version.

### CODE REVIEW

**Comment by mvdan** [comment]
Thanks for this PR! We want to support Go 1.20 until Go 1.22 is out, and the `go` directive in `go.mod` signals the language version we are using, so it could easily lead to us breaking people on Go 1.20 when we still want to support them in v0.7. I believe the Go toolchain also takes this version as a signal for a minimum version to use, so that wouldn't be a good signal to have either.

See https://github.com/cue-lang/cue/discussions/1937 as well.

**Comment by sivchari** [comment]
@mvdan 
Thanks for quickly comment ! I see and I appreciate that you said. Btw, do you plan v0.8 to support Go.1.22.0 ?

**Comment by mvdan** [comment]
CUE master should generally support Go master, since multiple of us use Go master as a daily driver. Whenever we release a CUE stable version, it should also support the latest Go stable version.

**Comment by sivchari** [comment]
Nice and thanks for good work. CUE helps my works 🥇

**Pull request closed without merging**
