### PR TITLE
doc/tutorial: fix typo in 55_defs.txt

### PR DESCRIPTION
**Pull request by obowersa**
Teeny tiny spelling fix which I noticed while going through the tutorial

### CODE REVIEW

**Comment by myitcv** [comment]
Thanks @obowersa - please can you [assert the DCO](https://github.com/cue-lang/cue/blob/master/doc/contribute.md#asserting-a-developer-certificate-of-origin)?

**Comment by myitcv** [comment]
Also, per the [commit message style guide](https://github.com/cue-lang/cue/blob/master/doc/contribute.md#good-commit-messages), please can you change the commit message to something like:

```
doc/tutorial: fix typo in 55_defs.txt
```

Thanks!

**Comment by obowersa** [comment]
I'll get this sorted later today! Apologies on the really low PR quality, I was half awake when I sort of raised it on autopilot.

**Comment by myitcv** [comment]
> Apologies on the really low PR quality, I was half awake when I sort of raised it on autopilot.

Absolutely no apologies required at all! Every project is slightly different contribution-guide wise. 

> I'll get this sorted later today!

Thanks very much! No rush at all.

**Comment by obowersa** [comment]
That should be it updated. Let me know if there's anything else which needs tweaked.

**Comment by myitcv** [comment]
Thanks, @obowersa. The one last thing that needs tweaking is the first line of the commit message, https://github.com/cue-lang/cue/pull/1489/commits/755332cb9d1b2eb6c7696a0c596c81db947b993b.

At the moment that first line reads:

```
Update 55_defs.txtpdate 55_defs.txt
```

whereas it needs to read something like:

```
doc/tutorial: fix typo in 55_defs.txt
```

The title of the PR is actually not important. 

To put this request in context, the reason this is useful is that someone looking at a commit immediately gets a good high-level summary of what is being changed, where, without having to read the body of the commit message. For examples, see the commits already "merged":

https://github.com/cue-lang/cue/commits/master

**Comment by obowersa** [comment]
Sorted. I could have sworn I amended the first line of the commit last night, but apparently I'm losing my mind

**Comment by myitcv** [comment]
@obowersa - thank you very much for your patience and perseverance. Whilst these might seem like small changes to be requesting, hopefully in the context of a project this size they make sense. I can assure you that they quickly become second nature!

**Review by myitcv — APPROVED** [review]

**Pull request closed without merging**
