### PR TITLE
typo fixed

### PR DESCRIPTION
**Pull request by zhelenskiy**

### CODE REVIEW

**Comment by myitcv** [comment]
@zhelenskiy thanks for the contribution. As you can see the DCO check has failed. Please refer to [the contribution guide](https://github.com/cue-lang/cue/blob/master/doc/contribute.md) for details on how to sign off your commits.

**Comment by zhelenskiy** [comment]
As setup is rather big for fixing, I would like someone with done setup to apply the similar commit. I think it easier for both sides.

**Comment by myitcv** [comment]
@zhelenskiy understood, thanks for flagging the issue in any case.

**Comment by zhelenskiy** [comment]
You are welcome!

**Pull request closed without merging**
