### PR TITLE
Fix typo in docstring

### PR DESCRIPTION
**Pull request by brandonbloom**

### CODE REVIEW

**Comment by myitcv** [comment]
Good spot, thanks @brandonbloom.

Please can you [assert the DCO](https://github.com/cue-lang/cue/blob/master/doc/contribute.md#asserting-a-developer-certificate-of-origin)?

**Comment by myitcv** [comment]
Also, per the [commit message style guide](https://github.com/cue-lang/cue/blob/master/doc/contribute.md#good-commit-messages), please can you change the commit message to something like:

```
cue/ast: fix typo in docstring
```

Thanks!

**Comment by brandonbloom** [comment]
Odd. I just copy/paste this here?

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

**Comment by brandonbloom** [comment]
fixed up commit

**Comment by myitcv** [comment]
> Odd. I just copy/paste this here?
> 
> fixed up commit

Thanks. I was similarly confused when I first contributed to a project that uses DCO! But it actually ends up being much more convenient than a CLA signed via some system that requires you to log in etc.

**Comment by myitcv** [comment]
Closed via https://github.com/cue-lang/cue/commit/f0d03f37402f3a17c6fe124051773420bd75ca64.

**Pull request closed without merging**
