### PR TITLE
cue/export/extract: fix comments with comprehensions

### LINKED ISSUE #2062: cue/comprehesions: comments lost with comprehensions
### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
v0.5.0-alpha.1.0.20221103093641-a4941ed62de0
</pre>

### Does this issue reproduce with the latest release?
yes

### What did you do?

The repro is as bellow:

```
# tip
go mod tidy
go run main.go
cmp stdout stdout.golden
-- go.mod --
module test-cue/lost-docs

go 1.19

require cuelang.org/go v0.5.0-alpha.1.0.20221103093641-a4941ed62de0

require (
	github.com/cockroachdb/apd/v2 v2.0.2 // indirect
	github.com/google/uuid v1.2.0 // indirect
	github.com/mpvl/unique v0.0.0-20150818121801-cbe035fff7de // indirect
	github.com/pkg/errors v0.8.1 // indirect
	golang.org/x/net v0.0.0-20220722155237-a158d28d115b // indirect
	golang.org/x/text v0.3.8 // indirect
	gopkg.in/yaml.v3 v3.0.1 // indirect
)
-- main.go --
package main

import (
	"fmt"

	"cuelang.org/go/cue"
	"cuelang.org/go/cue/cuecontext"
	"cuelang.org/go/cue/format"
)

var test = `
// hello
a: "a"
// hello2
if true {
	// hello3
	b: "v"
}
`

func main() {
	v := cuecontext.New().CompileString(test)
	b, err := format.Node(v.Syntax(cue.Docs(true)))
	if err != nil {
		panic(err)
	}
	fmt.Println(string(b))
	_, err = v.Fields()
	if err != nil {
		panic(err)
	}
}
-- repro.txt --
-- stdout.golden --
{
        // hello1
        a: "a"
        // hello2
        if true {
                // hello3
                b: "v"
        }
}
```

### What did you see instead?

And the result is like:

```

> go run main.go
[stdout]
{
        a: "a"
        if true {
                // hello3
                b: "v"
        }
}

> cmp stdout stdout.golden
--- stdout
+++ stdout.golden
@@ -1,7 +1,9 @@
 {
-       a: "a"
-       if true {
-               // hello3
-               b: "v"
-       }
+        // hello1
+        a: "a"
+        // hello2
+        if true {
+                // hello3
+                b: "v"
+        }
 }

FAIL: /var/folders/2n/0vszm3355n114dk2r_ln8vrh0000gp/T/testscript1695220691/repro.txt/script.txt:4: stdout and stdout.golden differ
error running repro.txt in /var/folders/2n/0vszm3355n114dk2r_ln8vrh0000gp/T/testscript1695220691/repro.txt
```

### PR DESCRIPTION
**Pull request by FogDong**
This fixes several comments bugs with comprehensions.

1. Fix the bug that comments lost on comprehensions.

2. Add comments in decl.

Fixes #2062

Signed-off-by: FogDong <dongtianxin.tx@alibaba-inc.com>

### CODE REVIEW

**Comment by myitcv** [comment]
cc @mpvl for guidance on whether this is the right fix or not.

**Comment by myitcv** [comment]
Marking as v0.5.0 to see if we can include this.

**Comment by myitcv** [comment]
@FogDong has confirmed this is not a blocker from their side.

**Comment by FogDong** [comment]
> @FogDong has confirmed this is not a blocker from their side.

We have fixed the bug in our fork version, but it's a blocker for us to use the community version.

**Comment by myitcv** [comment]
@FogDong - per @mpvl, this is a tricky problem to fix fully. 

We are iterating on potential fixes in parallel to your PR in https://review.gerrithub.io/c/cue-lang/cue/+/546866. But it's proving tricky.

We are therefore going to cut v0.5.0-beta.2 without this fix, and look to revisit.

**Comment by myitcv** [comment]
Thanks very much once again for proposing a fix here, @FogDong. The fix was quite a bit more involved, and Marcel has made the necessary adjustments in CL https://review.gerrithub.io/c/cue-lang/cue/+/546866 which just got submitted.

**Pull request closed without merging**
