### PR TITLE
cue/load: fix infinity loop on package import cycle

### LINKED ISSUE #849: cue/load: package cycles are not detected
_Originally opened by @grouville in https://github.com/cuelang/cue/issues/849_

### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
cue version 0.3.0-beta.7 darwin/amd64 (installed with brew)
</pre>

### Does this issue reproduce with the latest release?
Yes

### What did you do?

It seems that `cue eval` / `cue export` goes into an infinite loop when evaluating/exporting packages with cyclic inclusion

Here is a tree representation of a little implementation, to reproduce the error :
```bash
➜  test_infinite tree
.
├── cue.mod
│   ├── module.cue
│   ├── pkg
│   │   └── top.dev
│   │       ├── la
│   │       │   └── toto.cue
│   │       └── lo
│   │           └── tata.cue
│   └── usr
└── main.cue
```
---------
*main.cue* 
```cue
package main

import (
	"top.dev/lo"
)

test: {
    value: #JO & {
        test2: "top"
    }
}
```
---------
*module.cue* 
```cue
module: "main"
```
---------
*toto.cue*
```cue
package la

import (
	"top.dev/lo"
)

#LA: {
	test?: string
}
```
---------
*tata.cue*
```cue
package lo

import (
	"top.dev/la"
)

#JO: {
	test2?: string
}
```
----------
----------

*output*
```bash
➜  test time cue export
^C
cue export  325,33s user 8,33s system 173%!c(MISSING)pu 3:12,37 total
```

### What did you expect to see?

I'm not sure this is an issue. I think it is, but I might be wrong :
- With a broken field in the main (other test, same structure. Change the main.cue like that :
```cue
package main

import (
	"top.dev/lo"
)

test: {
    value: #JO & {
        test2: 1
    }
}
```
=> With this main, a validation error (test2 expects a string, and I provide an int)

- With the first main showed, a warning, or maybe not an infinite inclusion [I'm not sure if this is an expected behavior]

### What did you see instead?

An infinite loop

### PR DESCRIPTION
**Pull request by bozaro**
Fixes #849

### CODE REVIEW

**Comment by mvdan** [comment]
Sorry, what is this fixing? It would be best if you opened a bug report first, following the template to include a way to reproduce the issue.

**Comment by bozaro** [comment]
@mvdan, this PR fixes very old #849 issue.
I also add `cue/testdata/eval/issue849.txtar` testcase for this issue.

**Comment by mvdan** [comment]
Thanks. Could you please expand your commit message to explain the fix? At least what you're doing isn't obvious to me :)

**Comment by bozaro** [comment]
Changes:
 - move `Complete` after all files are parsed to ast (fix infinity loop at load stage): `cue/load/import.go` -> `cue/load/instances.go`;
 - build transitive dependencies after files registered (fix infinity recursion at build stage): `internal/core/runtime/build.go`;
 - add test for import cycle at load stage;
 - add test for import cycle at build stage.
 
If revert changes from `cue/load/import.go`, `cue/load/instances.go`, `internal/core/runtime/build.go` then both added tests are hangs.

**Comment by mvdan** [comment]
Thank you! I'll take a look. Out of curiosity, does this happen to fix https://github.com/cue-lang/cue/issues/2284 as well, or do you think it's a different issue altogether?

**Comment by bozaro** [comment]
Looks like this PR also fixes #2284 issue, although I don't see a loop in the test code.

**Comment by mvdan** [comment]
There is no loop in that issue - just one package that imports another package with the same name. Great to hear it's also fixed! I assume you also checked that this last added test also fails without your fix?

**Comment by bozaro** [comment]
> Great to hear it's also fixed! I assume you also checked that this last added test also fails without your fix?

Yes. Without this PR test stuck on load stage.

**Comment by mvdan** [comment]
Thanks! The changes look fine to me; do you want to squash your commits and write a good commit message explaining your changes and including all the "fixes" lines? In general we follow the guidelines at https://github.com/golang/go/wiki/CommitMessage.

**Comment by bozaro** [comment]
Squashed :)

**Comment by mvdan** [comment]
Thank you! I'll import into Gerrit and merge once Marcel has skimmed the changes, since I'm not super familiar with the package.

**Comment by rogpeppe** [comment]
Although this does technically fix the issue, it also makes cyclic imports work, which raises another question: _should_ a cyclic import produce an error or not?

Currently the spec is [clear on the matter](https://cuelang.org/docs/references/spec/#import-declarations):
> It is illegal for a package to import itself, directly or indirectly

So this PR isn't quite right, according to that.

It's possible we might want to change the spec, but that's a larger policy question.
For now, it would be better to make this an explicit error, I think.

**Comment by bozaro** [comment]
I couldn't figure out how to do a check for cyclic import without breaking the https://github.com/cue-lang/cue/issues/2284 fix.
From my point of view, allowing cyclic imports is less evil than an infinite loop at the loading stage.

**Comment by bozaro** [comment]
Looks like #2284 is differ bug. But this PR mask it.

**Comment by bozaro** [comment]
@rogpeppe, I created new PR with add packge import cycle error: https://github.com/cue-lang/cue/pull/2469

**Comment by mvdan** [comment]
Roger is right - I had not noticed that this was allowing cyclic package imports to work, which shouldn't per the documentation. Thanks for opening the other PR! We can focus on that one, then.

**Pull request closed without merging**
